SHOW FILE FORMATS IN SCHEMA CRYPTO_DB.TRANSFORMED;

CREATE OR REPLACE FILE FORMAT CRYPTO_DB.TRANSFORMED.MY_PARQUET_FORMAT
  TYPE = 'PARQUET'
  COMPRESSION = 'SNAPPY'
  BINARY_AS_TEXT = FALSE;


SELECT 
    $1,           -- This shows the RAW data object
    $1:market_cap, 
    $1:MARKET_CAP 
FROM @CRYPTO_DB.TRANSFORMED.MY_S3_STAGE
(FILE_FORMAT => 'CRYPTO_DB.TRANSFORMED.MY_PARQUET_FORMAT')
LIMIT 10;


SELECT 
    $1           -- This shows the RAW data object 
FROM @CRYPTO_DB.TRANSFORMED.MY_INTRA_DAY_S3_STAGE
(FILE_FORMAT => 'CRYPTO_DB.TRANSFORMED.MY_PARQUET_FORMAT')
LIMIT 10;

SELECT * FROM CRYPTO_DB.TRANSFORMED.CRYPTO_HISTORICAL_DATA;
SELECT * FROM CRYPTO_DB.TRANSFORMED.CRYPTO_INTRA_DAY_DATA;